package otameshi;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class SearchTest_JUnit {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    // Test name: search
    // Step # | name | target | value | comment
    // 1 | open | /jma/index.html |  |
    driver.get("https://www.jma.go.jp/jma/index.html");
    // 2 | click | xpath=//img[@alt='防災情報'] |  |
    driver.findElement(By.xpath("//img[@alt=\'防災情報\']")).click();
    // 3 | click | css=form:nth-child(2) > input |  |
    driver.findElement(By.cssSelector("form:nth-child(2) > input")).click();
    // 4 | type | css=form:nth-child(2) > input | 東京 |
    driver.findElement(By.cssSelector("form:nth-child(2) > input")).sendKeys("東京");
    // 5 | click | linkText=東京都 |  |
    driver.findElement(By.linkText("東京都")).click();
    // 6 | assertText | css=.breadcrumb-offices | 東京都の防災情報 |
    assertThat(driver.findElement(By.cssSelector(".breadcrumb-offices")).getText(), is("東京都の防災情報"));
    // 7 | setWindowSize | 955x737 |  |
    driver.manage().window().setSize(new Dimension(955, 737));
  }
}
